### PR TITLE
Translation suggestions for Spanish.

### PR DESCRIPTION
**Pull request by SalchiPapa**
Hello I noted some strange translations, so I wanted to fix them up, typing 🚀  is awesome!

```
|---------------------------------------------------------------|
| words | current | meaning | correction   | correction meaning |
|===============================================================|
| quit  | dejar   | leave   |  cerrar      | to quit            |
|---------------------------------------------------------------|
| off   | afuera  | outside | deshabilitar | disable            |
|---------------------------------------------------------------|
| on    | dentro  | inside  | habilitar    | enable             |
|---------------------------------------------------------------|
```

### CODE REVIEW

**Comment by mike-fabian** [comment]
Great, thank you very much! I merged it into my working branch, it will be in the next release.

**Comment by SalchiPapa** [comment]
Thank you very much!

**Comment by mike-fabian** [comment]
By the way, are you using Fedora? Do you have a Fedora account? If yes, you can also translate ibus-typing-booster using https://fedora.zanata.org/. 

But don’t worry if you don’t have a Fedora account, I am very happy about improvements of translations via pull requests as well.

**Comment by SalchiPapa** [comment]
I don't have one but will create one, I have some other corrections that I would like to contribute, thank you very much for all your support!

**Comment by mike-fabian** [comment]
Great, I added you for Spanish and Catalan! Any other languages you are interested in?

**Comment by SalchiPapa** [comment]
I am Mexican, I don't speak Catalan. I can only support Spanish. :smile:

**Comment by mike-fabian** [comment]
☺ I see you made some updates in zanata. Thank you very much, your updates will be in the upcoming 1.4.0 release.

**Pull request closed without merging**
