### PR TITLE
Update from Weblate

### PR DESCRIPTION
**Pull request by weblate**

### CODE REVIEW

**Comment by piotrdrag** [comment]
`pt_PT.po` is wrong. Is there a way to make Weblate push pt_PT translations to `pt.po` instead?

**Comment by mike-fabian** [comment]
If you click on "Start new translation" on https://translate.stg.fedoraproject.org/new-lang/ibus-typing-booster/app/ "pt" is also available. Maybe the admin of weblate could move the pt_PT translations which exist already now to "pt"?

**Comment by Jibec** [comment]
Renaming was easy, here is the process:

open the language in weblate
export the po file
delete the language
add a new translation
import the po file (use the contributor name and email for credit)

**Comment by mike-fabian** [comment]
> Renaming was easy, here is the process:
> 
> open the language in weblate
> export the po file
> delete the language
> add a new translation
> import the po file (use the contributor name and email for credit)

Great! Thank you!

**Pull request merged**
