### PR TITLE
Update for README.md

### PR DESCRIPTION
**Pull request by joe247**
Hi Mike,
I've done a thorough update to the _README_ file. There were few typos, some redundancy and not-so good looking table. I re-wrote tables to fit the markdown syntax which really looks nice now. Please do mention any more changes that needs to be made. I'll follow up as and when I get time.

### CODE REVIEW

**Comment by mike-fabian** [comment]
Why renaming from README.md to Readme.md?

**Comment by mike-fabian** [comment]
Please  don’t change the part whith the table of the key bindings and mouse bindings.

Because that part is generated from

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#key-bindings

using w3m.  

That way, I can keep  the keybindings shown README.md and in the online documentation in 
http://mike-fabian.github.io/ibus-typing-booster/documentation.html#key-bindings
in sync.

If  you manually edit this in README.md, it needs to be kept in sync by editing in two places manually.

**Comment by mike-fabian** [comment]
I wonder if there is some tool to create a plain text file, readable with "less" from a .md file with some tool.

Currently, README.md is just copied to README during build. If there is a tool to create something readable with less from a README.md then at least we would not have to edit in 3 places but only in 2.

**Comment by joe247** [comment]
> I wonder if there is some tool to create a plain text file, readable with "less" from a .md file with some tool.

Can you please tell what `readable with "less"` means?

> Currently, README.md is just copied to README during build.

But why do you need to do that for a successful build?

**Comment by mike-fabian** [comment]
> > I wonder if there is some tool to create a plain text file, readable with "less" from a .md file with some tool.
> 
> Can you please tell what `readable with "less"` means?

“less” is a command line tool to  view simple text files.

You can just type "less README" in a terminal on Linux and view the file.
.md files typically don’t look nice when viewed with less. 

> > Currently, README.md is just copied to README during build.
> 
> But why do you need to do that for a successful build?

Otherwise automake complains, see this commit:

https://github.com/mike-fabian/ibus-typing-booster/commit/b0d588f9908d43fac2f51256f73d58e1f531dcea

**Comment by mike-fabian** [comment]
Without a README, it is not conforming to the traditional Gnu standard.

And having a README which is readable using a simple text editor or less is also nice.

As your changes to README.md look nice in github,  I am trying to find a way to generate a somewhat readable README from README.md automatically. If I cannot do that, than I’ll add a separate README to my repository again and edit that one manually as well.

I don’t like this very much because each time something changes which affects the table of the key bindings, the mouse bindings, or something else in the README's, one has to edit in several places and keep everything in sync. 

But maybe I cannot avoid that  and having the README.md look nice on github is also good, maybe that is more important.

**Comment by mike-fabian** [comment]
So I think I’ll take your changes and try to produce a somewhat readable README somehow. 

I moved already moved the links from the bottom of your README.md to the place where the link is mentioned, like this:

```
-The project was started in 2010 for [Fedora 15][1]. The original purpose was to make typing o
f Indic languages easier and faster by providing completion and spell checking suggestions.
+The project was started in 2010 for [Fedora 15](https://en.wikipedia.org/wiki/Fedora_version_
history#Fedora_15). The original purpose was to make typing of Indic languages easier and fast
er by providing completion and spell checking suggestions.
```

and remove the
```
-[1]: https://en.wikipedia.org/wiki/Fedora_version_history#Fedora_15
``` 

a the bottom.

That makes no difference when viewing the file on github, the links still work, but it makes it much easier to see which link belongs to which part  of the text when viewing with "less".

```

**Comment by joe247** [comment]
> “less” is a command line tool to view simple text files.

Yes I figured it out a little later... :)

> Without a README, it is not conforming to the traditional Gnu standard.

> Otherwise automake complains, see this commit:

Ok I see the point...

> So I think I’ll take your changes and try to produce a somewhat readable README somehow.

I think I can write a script which takes README.md and creates a readable README... (but it will take some time)

**Comment by joe247** [comment]
> I moved already moved the links from the bottom of your README.md to the place where the link is mentioned, like this:

I've a doubt (a bit off-topic) these changes you made are they in 'git' terms staged or in working directory? (It's definitely not committed because I don't see change in the README.md fork)

**Comment by mike-fabian** [comment]
> > So I think I’ll take your changes and try to produce a somewhat readable README somehow.
> 
> I think I can write a script which takes README.md and creates a readable README... (but it will take some time)

I will also have a look, using “pandoc” seems promising:

https://pandoc.org/getting-started.html

I played with this a bit and it looks like with using pandoc to
convert to html and when w3m to convert to plain text, it should be
doable somehow.

**Comment by mike-fabian** [comment]
I added these rules to Makefile.am:

```
+README: README.html
+       w3m -cols 78 -o display_borders=1 -o display_link_number=1 $< > $@
+
+README.html: README.md
+       pandoc -f gfm -t html --standalone --self-contained --metadata pagetitle="IBus-typing-booster README" $< > $@
```

Now README.html and README can be generated from README.md with

```
make README.html
make README
```

The results look OK, so it is enough to edit README.md manually.

**Comment by mike-fabian** [comment]
Included in:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.7.7

closing.

**Pull request closed without merging**
