### PR TITLE
Fix icon transparency

### PR DESCRIPTION
**Pull request by ferdnyc**
The PNG versions of the app icons had, frankly, abysmal transparency, with tons of aliasing artifacts that made them look quite terrible against a dark background. This PR regenerates all of the icons with full transparency preserved from the original SVG, and as a bonus raises the detail of the `256x256` pixel version so that it's less blurry. 

Here's a before/after of the `48x48` version, blown up and placed side-by-side against a transparent background in Inkscape.

image

### CODE REVIEW

**Comment by mike-fabian** [comment]
How did  you generate the png files from the svg? 
I just would like to know how to do it right. If I remember correctly, I used

```
convert ibus-typing-booster.svg -geometry 128x128 ibus-typing-booster.png
```

to do the conversion. "convert" is from ImageMagick.

**Comment by mike-fabian** [comment]
Ah, I see it is in the commit message! Thank you!

**Comment by ferdnyc** [comment]
Yeah, sorry, I meant to include that here, too.

The conversion and DPI adjustment can be done all in one command, too (my Fedora PR adds this one-liner to the spec file's build process):
```sh
for size in 16 22 32 48 64 128 256; do
  convert -background none -density 1024 -resize "${size}x${size}" \
   ibus-typing-booster.svg -density 96 "${size}x${size}/ibus-typing-booster.png"
done
```

That renders the bitmap with full transparency and maximum possible detail. (The SVG file is internally dimensioned `128x128 px`; `convert` respects that and renders the `256x256` icon at half-resolution unless it's overridden.) It also sets the output PNG's metadata to a nice, standard 96 DPI — useful when importing the icons, since without that adjustment the PNGs import into Inkscape almost microscopically small.

**Comment by mike-fabian** [comment]
Merged into: https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.6.2

**Pull request closed without merging**
